name: ADD
description: Architecture Definition Document
labels: ['ADD']
assignees:
  - TorinAsakura
body:
  - type: textarea
    id: target
    attributes:
      label: Цель
      description: Основная цель
    validations:
      required: true
  - type: textarea
    id: artifacts
    attributes:
      label: Артефакты
      description: 'Что станет результатом'
    validations:
      required: true
  - type: textarea
    id: limitations
    attributes:
      label: Ограничения
      description: 'Что ограничивает нас при решении этой задачи, нужно что-то где-то переделать, или написать для реализации'
    validations:
      required: true
  - type: textarea
    id: architecture
    attributes:
      label: Архитектура
      description: Схемы
    validations:
      required: true
  - type: textarea
    id: components
    attributes:
      label: Список компонентов
      description: Компоненты, которые родятся вследствии
    validations:
      required: true
  - type: textarea
    id: roadmap
    attributes:
      label: Дорожная карта
      description: Список с чекбоксами
    validations:
      required: true
