name: ADR
description: Architecture Decision Record
labels: ['ADR']
assignees:
  - TorinAsakura
body:
  - type: textarea
    id: context
    attributes:
      label: Контекст
      placeholder: |
        - мы не планируем разрабатывать свои библиотеки и компоненты
        - мы не планируем делать что-то нестандартное и в дальнейшем трудно поддерживаемое
        - в качестве разработчиков административных интерфейсов планируем привлекать backend разработчиков
        - на стороне административных интерфейсов зачастую будет реализована бизнес логика, чем какой-то сложный пользовательский UI
        Было предложение использовать TypeScript в качестве языка разработки, а также AntDesign в качестве UI Kit.
        Основные преимущества TypeScript:
        - типизация данных, что в свою очередь сокращает множество ошибок на этапе компиляции проекта - проект попросту не соберется, в то время как написание на чистом Javascript вызывает проблемы в realtime (т.е. пользователь может наткнуться на проблему уже на продакшене, даже после тестирования, т.к. невозможно предусмотреть все кейсы заранее).
        - язык дает множество привычных для backend разработчиков конструкций языка, упрощающих погружение и освоение языка, в отличии от того же чистого Javascript
        - использование делает код более читабельным и лаконичным, язык обратно совместим с Javascript
        - реализация принципов ООП
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Решение
      placeholder: |
        В качестве технологий для реализации административных интерфейсов использовать:
        - [Vue.js](https://vuejs.org/) в качестве веб фреймворка
        - [TypeScript](https://www.typescriptlang.org/) в качестве языка программирования
        - [AntDesign Vue](https://www.antdv.com/docs/vue/introduce/) в качестве UI Kit
    validations:
      required: true
  - type: textarea
    id: aftermath
    attributes:
      label: Последствия
      placeholder: |
        - Отделу дизайнеров необходимо проектировать визуальные интерфейсы с учетом выбранных компонент AntDesign Vue UI Kit
        - Разработчикам необходимо дополнительно изучать Typescript, что повысит время онбоардинга нового человека в команду
    validations:
      required: true
